# Generated by Django 3.2.18 on 2023-07-30 12:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('market', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='name2',
            field=models.CharField(max_length=20, null=True, verbose_name='テスト'),
        ),
    ]
