# Generated by Django 3.2.18 on 2023-09-13 03:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('market', '0006_product_is_bid'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='deadline',
            field=models.DateTimeField(blank=True, null=True, verbose_name='入札期限'),
        ),
    ]
