# Generated by Django 3.2.18 on 2023-09-14 11:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('market', '0009_auto_20230914_2024'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='price',
            field=models.IntegerField(blank=True, null=True, verbose_name='希望売却価格'),
        ),
    ]
