# Generated by Django 3.2.18 on 2023-09-14 11:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('market', '0010_alter_product_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='name',
            field=models.CharField(blank=True, max_length=20, verbose_name='カテゴリ名'),
        ),
    ]
