# Generated by Django 3.2.18 on 2023-09-18 05:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('market', '0013_alter_product_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='is_bid',
            field=models.BooleanField(default=None, verbose_name='入札できる'),
        ),
    ]
