# Generated by Django 3.2.18 on 2023-09-18 05:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('market', '0014_alter_product_is_bid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='is_bid',
            field=models.BooleanField(default=False, verbose_name='入札できる'),
        ),
    ]
