# Generated by Django 3.2.18 on 2023-09-24 05:23

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('market', '0015_alter_product_is_bid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.ForeignKey(blank=True, default=1, on_delete=django.db.models.deletion.CASCADE, to='market.category', verbose_name='カテゴリ'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='product',
            name='deadline',
            field=models.DateTimeField(blank=True, default=django.utils.timezone.now, verbose_name='入札期限'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='product',
            name='price',
            field=models.IntegerField(blank=True, default=0, verbose_name='希望売却価格'),
            preserve_default=False,
        ),
    ]
