# Generated by Django 3.2.18 on 2023-10-01 05:15

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('market', '0016_auto_20230924_1423'),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dt', models.DateTimeField(default=django.utils.timezone.now, verbose_name='注文日時')),
                ('session_id', models.TextField(verbose_name='session id')),
                ('payment_dt', models.DateTimeField(blank=True, null=True, verbose_name='支払い日時')),
                ('delivery_dt', models.DateTimeField(blank=True, null=True, verbose_name='配送日時')),
                ('product', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='market.product', verbose_name='商品')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='購入希望者')),
            ],
        ),
    ]
